# Generated by Django 3.2.6 on 2022-04-20 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incomeplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incometype', models.CharField(max_length=200, verbose_name='incomeplans')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='myincome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inconmedate', models.DateField(auto_created=True)),
                ('incomeAmount', models.CharField(max_length=200)),
                ('incometype', models.CharField(max_length=200)),
                ('incomesource', models.CharField(max_length=2000)),
                ('incomeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['inconmedate'],
            },
        ),
    ]
