# Generated by Django 3.2.6 on 2022-09-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myincome',
            options={'ordering': ['-inconmedate']},
        ),
        migrations.AlterField(
            model_name='myincome',
            name='incomeAmount',
            field=models.FloatField(max_length=200),
        ),
    ]
