# Generated by Django 3.2.6 on 2022-04-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulkemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmailSubject', models.CharField(max_length=50)),
                ('Replyto', models.EmailField(max_length=50)),
                ('Emailto', models.EmailField(default='skyl@gmail.com', max_length=254)),
                ('fromEmail', models.EmailField(max_length=70)),
                ('body', models.TextField(default='testing body', max_length=300)),
            ],
        ),
    ]
